### ISSUE TITLE
[DOUBT] Set players of a team on the Tab List.

### ISSUE THREAD

**Issue by AlexMartSch** [kacperduras/ProtocolTab#10]
> I am sorry for my bad english.

What I wanted to do was insert a list of players for each slot in the TabList.

I came to a conclusion, which is the following:
However, I did not know how to make each player stay in each slot.

```
for (String key : TeamSpectatorKeySet()) {
  Player player = Bukkit.getPlayer(key);
  ProtocolTabAPI.getTablist(online).setSlot(¿X? ,"&4A: &7"+player.getName());
}
```

However, I have managed to solve my problem with a simple solution.

```
int slot = 1;
for (String key : TeamAKeySet()) 
{
	Player player = Bukkit.getPlayer(key);

	ProtocolTabAPI.getTablist(online).setSlot(slot, player.getDisplayName());
	slot += 1;
}
```
My problem is already solved, sorry for the lost time.

Thanks for all.

**Comment by LosTigeros** [comment]
Can you write that again but in proper english? Idfk what've you writed there :X

**Comment by kacperduras** [comment]
@LosTigeros +1

@AlexBanPer Hi, thanks you for your issue. I don't understand your idea (really, I read this text many times and nothing). Can you tell me again more easily and more clearly? Thanks a lot!

**Comment by kacperduras** [comment]
```
My problem is already solved, sorry for the lost time.

Thanks for all.
```

No problem @AlexBanPer ;)
